
export default function key() {
    return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2dm15aGxkdWNmbGFreXlub2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDEwNDA0MDUsImV4cCI6MjAxNjYxNjQwNX0.6OP7tGh4dLUBkkCc_qaoH1WQFqxQZPwt-DaLXAuUixs";
}